In [5]:
import pandas as pd

In [1]:
import numpy as np

In [6]:
df = pd.read_csv('german_credit_data (1).csv')

In [7]:
df.head()

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose
0,0,67,male,2,own,NaN,little,1169,6,radio/TV
1,1,22,female,2,own,little,moderate,5951,48,radio/TV
2,2,49,male,1,own,little,NaN,2096,12,education
3,3,45,male,2,free,little,little,7882,42,furniture/equipment
4,4,53,male,2,free,little,little,4870,24,car

In [8]:
df.rename(columns={'Unnamed: 0': 'ID'}, inplace=True)

In [12]:
df.head(10)

,ID,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose
0,0,67,male,2,own,NaN,little,1169,6,radio/TV
1,1,22,female,2,own,little,moderate,5951,48,radio/TV
2,2,49,male,1,own,little,NaN,2096,12,education
3,3,45,male,2,free,little,little,7882,42,furniture/equipment
4,4,53,male,2,free,little,little,4870,24,car
5,5,35,male,1,free,NaN,NaN,9055,36,education
6,6,53,male,2,own,quite rich,NaN,2835,24,furniture/equipment
7,7,35,male,3,rent,little,moderate,6948,36,car
8,8,61,male,1,own,rich,NaN,3059,12,radio/TV
9,9,28,male,3,own,little,moderate,5234,30,car

In [11]:
df.isnull().sum()

ID                    0
Age                   0
Sex                   0
Job                   0
Housing               0
Saving accounts     183
Checking account    394
Credit amount         0
Duration              0
Purpose               0
dtype: int64

In [13]:
df["Saving accounts"].fillna("no_info", inplace=True)
df["Checking account"].fillna("no_info", inplace=True)

In [14]:
df.isnull().sum()

ID                  0
Age                 0
Sex                 0
Job                 0
Housing             0
Saving accounts     0
Checking account    0
Credit amount       0
Duration            0
Purpose             0
dtype: int64

In [15]:
df = pd.get_dummies(df, drop_first=True)

In [17]:
df.head()

,ID,Age,Job,Credit amount,Duration,Sex_male,Housing_own,Housing_rent,Saving accounts_moderate,Saving accounts_no_info,...,Checking account_moderate,Checking account_no_info,Checking account_rich,Purpose_car,Purpose_domestic appliances,Purpose_education,Purpose_furniture/equipment,Purpose_radio/TV,Purpose_repairs,Purpose_vacation/others
0,0,67,2,1169,6,True,True,False,False,True,...,False,False,False,False,False,False,False,True,False,False
1,1,22,2,5951,48,False,True,False,False,False,...,True,False,False,False,False,False,False,True,False,False
2,2,49,1,2096,12,True,True,False,False,False,...,False,True,False,False,False,True,False,False,False,False
3,3,45,2,7882,42,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,4,53,2,4870,24,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False

In [19]:
df = df.astype(int)

In [20]:
df.head()

,ID,Age,Job,Credit amount,Duration,Sex_male,Housing_own,Housing_rent,Saving accounts_moderate,Saving accounts_no_info,...,Checking account_moderate,Checking account_no_info,Checking account_rich,Purpose_car,Purpose_domestic appliances,Purpose_education,Purpose_furniture/equipment,Purpose_radio/TV,Purpose_repairs,Purpose_vacation/others
0,0,67,2,1169,6,1,1,0,0,1,...,0,0,0,0,0,0,0,1,0,0
1,1,22,2,5951,48,0,1,0,0,0,...,1,0,0,0,0,0,0,1,0,0
2,2,49,1,2096,12,1,1,0,0,0,...,0,1,0,0,0,1,0,0,0,0
3,3,45,2,7882,42,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,4,53,2,4870,24,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [23]:
df.columns

Index(['ID', 'Age', 'Job', 'Credit amount', 'Duration', 'Sex_male',
       'Housing_own', 'Housing_rent', 'Saving accounts_moderate',
       'Saving accounts_no_info', 'Saving accounts_quite rich',
       'Saving accounts_rich', 'Checking account_moderate',
       'Checking account_no_info', 'Checking account_rich', 'Purpose_car',
       'Purpose_domestic appliances', 'Purpose_education',
       'Purpose_furniture/equipment', 'Purpose_radio/TV', 'Purpose_repairs',
       'Purpose_vacation/others'],
      dtype='object')